import {createPlatformer,stepPlatformer,drawPlatformer,platformerSummary} from './platformer-engine.js';
import {TOWER_TYPES,createNightwatch,stepNightwatch,nightwatchAction,drawNightwatch,nightwatchSummary,nightwatchCellAt} from './nightwatch-engine.js';
import {loadPlatformerArt} from './platformer-renderer.js';
import {platformerLanding,platformerSectorRail} from './platformer-presentation.js';
import {calculateRunScore,formatScore} from './score-store.js';

export const adventureIds=['platformer','nightwatch'];
export const adventureMeta={
 platformer:{no:'20',title:'时光跃迁',accent:'发条群岛',color:'#b63f32',mark:'跃',genre:'横版动作 · 平台闯关',desc:'战战闯入六重炼狱。断层冲刺、连塌窄桥与高炉机关，跨过最后一道熔心关口。',goal:'穿过六段炼狱群岛，抵达熔心终点。',metric:'收集齿轮',key:'coins',modes:{extreme:['地狱远征','六段长关卡 · 2 枚机芯 · 2 处检查点'],endless:['无尽裂隙','双机芯开局，险境持续升级'],shadow:['一命绝境','同一条炼狱路线，一次失误结束']},tips:['A / D 或 ← → 移动，空格 / W / ↑ 起跳','短按低跳，长按高跳；从上方踩中甲虫可反弹','Shift / X 冲刺越过宽裂缝；橙色预警后，高炉会喷发']},
 nightwatch:{no:'21',title:'时光守夜',accent:'最后街区',color:'#ad7045',mark:'守',genre:'策略塔防 · 五路尸潮',desc:'灯亮着，街区就在。安排供电、布下火力，把最后一道防线守到天明。',goal:'消灭 10 波尸潮，守住街区大门。',metric:'消灭僵尸',key:'kills',modes:{extreme:['守到天明','10 波攻防 · 四类设施 · 三段升级'],endless:['无尽长夜','逐波增援，考验布阵与资源运营'],shadow:['末日围城','12 波高压攻势，独立成绩记录']},tips:['选择设施，再点击空地建造；1—4 快速选设施','点击已有设施查看升级与回收；路障放在火力前方','部署完成后放行尸潮；发电机在战斗中持续供能']}
};
export const adventureModeLabel=(id,mode)=>adventureMeta[id]?.modes[mode]?.[0]||mode;
export function adventureTiles(){return adventureIds.map(id=>{const m=adventureMeta[id];return `<article class="game-tile ng-tile adventure-tile adventure-tile-${id}" style="--wave:${m.color}"><span class="game-number">${m.no}</span><div><small>新卡带 · ${m.genre}</small><h3>${m.title}：${m.accent}</h3><p>${m.desc}</p></div><button data-open-adventure="${id}">装入游戏 →</button></article>`}).join('')}
export function adventureFeatured(){return `<section class="adventure-discovery" aria-label="全新冒险"><span>两枚新卡带</span><button data-open-adventure="platformer"><b>发条群岛</b><small>跳跃闯关</small><span>↗</span></button><button data-open-adventure="nightwatch"><b>最后街区</b><small>尸潮塔防</small><span>→</span></button></section>`}
export function adventureLanding(id){const m=adventureMeta[id];if(id==='platformer')return platformerLanding(m);return `<main id="main" class="adventure-landing" style="--adv:${m.color}">
 <section class="adventure-intro"><div class="adventure-intro-copy"><span class="adventure-serial">CARTRIDGE ${m.no} / ${m.genre}</span><h1>${m.title}<span>${m.accent}</span></h1><p>${m.desc}</p><button class="primary" data-adventure-start="${id}" data-adventure-mode="extreme">${id==='platformer'?'启程冒险':'开始守夜'} →</button><div class="adventure-tags"><span>原创像素场景</span><span>键盘 / 触控</span><span>真实事件计分</span></div></div><div class="adventure-preview-shell"><header><b>${id==='platformer'?'ISLAND EXPEDITION':'NIGHT WATCH'}</b><span>TM–${m.no}</span></header><canvas id="adventure-preview" width="960" height="540" aria-label="${m.accent}场景预览"></canvas><footer><span>${m.goal}</span><span>场景预览</span></footer></div></section>
 <section class="adventure-mode-section"><header><h2>选择你的挑战</h2><p>按目标通关，每种模式独立记录。</p></header><div class="adventure-mode-list">${Object.entries(m.modes).map(([mode,[name,desc]],i)=>`<button data-adventure-start="${id}" data-adventure-mode="${mode}" class="adventure-mode"><span class="adventure-mode-index">${['01','∞','!'][i]}</span><span><b>${name}</b><small>${desc}</small></span><span aria-hidden="true">↗</span></button>`).join('')}</div></section>
 <section class="adventure-manual"><h2>${id==='platformer'?'学会起跳，再走远一点。':'第一座塔，决定今晚的打法。'}</h2><ol>${m.tips.map((tip,i)=>`<li><span>0${i+1}</span>${tip}</li>`).join('')}</ol></section></main>`}

export function adventureGameView(id,mode){const m=adventureMeta[id],platform=id==='platformer',goal=mode==='endless'?(platform?'群岛不断延伸，挑战最远距离。':'抵御不断升级的尸潮，挑战最多波次。'):!platform&&mode==='shadow'?'消灭 12 波高压尸潮，守住街区大门。':m.goal;return `<main id="main" class="game-page adventure-game ${id}-game" style="--adv:${m.color}" data-adventure="${id}">
 <div class="adventure-console"><header class="adventure-game-header"><button data-open-adventure="${id}" aria-label="退出到模式选择">←</button><div><small>TM–${m.no} / ${adventureModeLabel(id,mode)}</small><h1>${m.title}<span>${m.accent}</span></h1></div><div class="adventure-time"><small>${platform?'本局用时':'战斗用时'}</small><b id="adv-clock">00:00</b></div><button data-adv-pause aria-label="暂停游戏">暂停</button><button data-adv-sound aria-label="开启游戏音效" aria-pressed="false">音效：关</button></header>
 <div class="adventure-hud"><div><small>本局积分</small><b id="adv-score">0</b></div><div><small id="adv-primary-label">${platform?'生命':'可用电力'}</small><b id="adv-primary">—</b></div><div><small id="adv-secondary-label">${platform?'齿轮':'街区大门'}</small><b id="adv-secondary">—</b></div><div class="adventure-progress"><span id="adv-stage">${platform?'第一段群岛':'准备布防'}</span><i><em id="adv-progress"></em></i></div></div>
 ${platform&&mode!=='endless'?platformerSectorRail():''}<div class="adventure-screen"><canvas id="adventure-canvas" width="960" height="540" tabindex="0" aria-label="${platform?'发条群岛游戏画面。方向键移动，空格跳跃，X 冲刺。':'最后街区游戏画面。方向键选择格子，空格建造，1 到 4 选择设施。'}"></canvas><div class="adventure-overlay" id="adv-overlay"><div><span>${platform?`战战 · ${adventureModeLabel(id,mode)} v2`:'这条街，今晚交给你。'}</span><h2 id="adv-overlay-title">${platform?(mode==='endless'?'没有终点，只有更远':mode==='shadow'?'只有一次机会':'六重炼狱，现在出发'):'先布防，再迎战'}</h2><p id="adv-overlay-copy">${platform?'方向键移动，长按空格高跳，X 冲刺。宽裂缝必须冲刺；高炉亮橙灯后及时避开。':'先选设施，再点空地。前排路障、后排火力，留出电力建设发电机。'}</p><button class="primary" data-adv-resume>开始${platform?'挑战':'布防'} →</button></div></div></div>
 <div class="adventure-status"><i></i><span id="adv-notice" role="status">${goal}</span><small>本机真实事件计分</small></div>
 ${platform?`<div class="adventure-controls"><div class="adventure-move"><button data-adv-key="left" aria-label="向左移动">←</button><button data-adv-key="right" aria-label="向右移动">→</button></div><p>长按高跳 · 踩敌反弹<br><small>A / D 移动 · 空格跳跃 · X / Shift 冲刺</small></p><div class="adventure-actions"><button data-adv-key="dash">冲刺 <small>X</small></button><button data-adv-key="jump" class="jump-key">起跳 <small>SPACE</small></button></div></div>`:`<div class="tower-command"><div class="tower-builds" aria-label="选择防御设施">${TOWER_TYPES.map((t,i)=>`<button data-tower="${t.id}" aria-pressed="${i===0}" class="${i===0?'selected':''}"><span class="tower-icon tower-icon-${t.id}" aria-hidden="true"></span><span><b>${t.name}</b><small>${t.cost} 电力 · ${i+1}</small></span></button>`).join('')}</div><div class="tower-selection"><p id="tower-selection-copy">选择设施，再点击空地。</p><div><button data-tower-action="upgrade" disabled>升级设施</button><button data-tower-action="sell" disabled>回收设施</button><button data-tower-wave class="primary">放行第 1 波 →</button></div></div></div>`}
 <details class="adventure-help"><summary>操作与通关规则</summary><p>${goal} ${m.tips.join('。')}。P / Esc 暂停，离开页面自动暂停。${platform?(mode==='shadow'?'一命模式没有复活。':'仅有 2 枚机芯；受伤或坠落会扣除机芯。坠落返回检查点，检查点不回血。'):'僵尸突破会损伤街区大门，大门生命归零后结束。'}无尽模式可在暂停面板结算成绩。</p></details></div></main>`}

let active=null;
const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function seeded(value){let n=2166136261;for(const c of String(value))n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0}
export function stopAdventure(){if(!active)return;active.controller?.abort();cancelAnimationFrame(active.raf);active.audio?.close().catch(()=>{});active=null}
export function mountAdventurePreview(id){stopAdventure();const canvas=document.querySelector('#adventure-preview');if(!canvas)return;const ctx=canvas.getContext('2d'),platform=id==='platformer',s=platform?createPlatformer('extreme',17):createNightwatch('extreme',17);if(!platform){nightwatchAction(s,{type:'build',row:2,col:0,tower:'generator'});nightwatchAction(s,{type:'build',row:1,col:2,tower:'shooter'});nightwatchAction(s,{type:'build',row:3,col:2,tower:'frost'});nightwatchAction(s,{type:'build',row:2,col:4,tower:'barricade'});}const draw=platform?drawPlatformer:drawNightwatch;draw(ctx,s,960,540);if(platform)loadPlatformerArt().then(()=>{if(canvas.isConnected)draw(ctx,s,960,540)});}
export function mountAdventure(id,mode,onFinish,seed='1'){
 stopAdventure();const canvas=document.querySelector('#adventure-canvas');if(!canvas)return;
 const platform=id==='platformer',s=platform?createPlatformer(mode,seeded(seed)):createNightwatch(mode,seeded(seed)),summary=platform?platformerSummary:nightwatchSummary,draw=platform?drawPlatformer:drawNightwatch;
 const controller=new AbortController(),signal=controller.signal,keys={},pointers=new Map(),held=new Set(),ctx=canvas.getContext('2d'),dpr=Math.min(2,devicePixelRatio||1);
 canvas.width=960*dpr;canvas.height=540*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=platform;if(platform)loadPlatformerArt();
 s.reducedMotion=typeof matchMedia==='function'&&matchMedia('(prefers-reduced-motion: reduce)').matches;
 const run={s,controller,raf:0,paused:true,started:false,finished:false,audio:null,sound:false};active=run;
 const q=sel=>document.querySelector(sel),on=(el,type,fn)=>el?.addEventListener(type,fn,{signal}),overlay=q('#adv-overlay');
 let tool=TOWER_TYPES[0].id,cell={row:2,col:0},last=performance.now(),carry=0,hudCarry=0,lastEvents=0,feedback='',feedbackUntil=0;
 const setText=(sel,v)=>{const el=q(sel);if(el&&el.textContent!==String(v))el.textContent=v};
 const clearKeys=()=>{held.clear();pointers.clear();Object.keys(keys).forEach(k=>keys[k]=false);document.querySelectorAll('[data-adv-key]').forEach(b=>b.classList.remove('held'))};
 const updateKeys=()=>{for(const key of ['left','right','jump','dash'])keys[key]=held.has(key)||[...pointers.values()].includes(key)};
 const beep=()=>{if(!run.sound||!run.audio)return;const osc=run.audio.createOscillator(),gain=run.audio.createGain();osc.type='triangle';osc.frequency.value=platform?620:190;gain.gain.setValueAtTime(.035,run.audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,run.audio.currentTime+.08);osc.connect(gain).connect(run.audio.destination);osc.start();osc.stop(run.audio.currentTime+.08)};
 const updateHud=()=>{
  const v=summary(s),points=calculateRunScore({gameId:id,mode,outcome:s.won?'clear':'failed',durationMs:Math.round(s.elapsed*1000),metrics:v.metrics});
  setText('#adv-clock',fmt(s.elapsed));setText('#adv-score',formatScore(points));setText('#adv-primary-label',platform?v.primaryLabel:'可用电力');setText('#adv-primary',platform?v.primaryValue:Math.floor(v.energy));setText('#adv-secondary-label',v.secondaryLabel);setText('#adv-secondary',v.secondaryValue);
  setText('#adv-stage',platform?`${mode==='endless'?'裂隙':`第 ${v.phase} / 6 区`} · ${Math.round(v.progress)}%`:`第 ${v.wave} / ${mode==='endless'?'∞':v.totalWaves} 波`);q('#adv-progress').style.width=`${Math.max(0,Math.min(100,v.progress))}%`;
  if(platform){document.querySelectorAll('[data-platformer-sector]').forEach(el=>{const i=Number(el.dataset.platformerSector);el.classList.toggle('active',i===s.sectorIndex);el.classList.toggle('complete',i<s.sectorIndex)});const dash=q('[data-adv-key="dash"] small');if(dash)dash.textContent=s.player.dashCooldown>0?`${s.player.dashCooldown.toFixed(1)}s`:'X / SHIFT';}
  setText('#adv-notice',performance.now()<feedbackUntil?feedback:v.notice);
  const events=platform?v.metrics.coins+v.metrics.stomps:v.metrics.kills;if(events>lastEvents)beep();lastEvents=events;
  if(!platform){
   const selected=v.selected,t=TOWER_TYPES.find(x=>x.id===tool);setText('#tower-selection-copy',selected?`${selected.name} Lv.${selected.level} · 耐久 ${Math.ceil(selected.hp)} / ${selected.maxHp}`:`${t.name} · ${t.description}`);
   const up=q('[data-tower-action="upgrade"]'),sell=q('[data-tower-action="sell"]'),wave=q('[data-tower-wave]');up.disabled=run.paused||!selected||selected.level>=3||v.energy<(selected.upgradeCost||0);sell.disabled=run.paused||!selected;up.textContent=selected&&selected.level<3?`升级 · ${selected.upgradeCost} 电力`:selected?'已达满级':'升级设施';sell.textContent=selected?`回收 +${selected.sellValue}`:'回收设施';wave.disabled=run.paused||!v.canStartWave;wave.textContent=v.canStartWave?`放行第 ${v.wave+1} 波 →`:'尸潮进行中';
   document.querySelectorAll('[data-tower]').forEach(b=>{const def=TOWER_TYPES.find(t=>t.id===b.dataset.tower);b.classList.toggle('unaffordable',v.energy<def.cost)});
  }
 };
 const finish=(aborted=false)=>{if(run.finished)return;run.finished=true;run.paused=true;clearKeys();const v=summary(s);controller.abort();cancelAnimationFrame(run.raf);run.audio?.close().catch(()=>{});onFinish({id,mode,win:!aborted&&s.won,time:s.elapsed,metrics:v.metrics,endedReason:aborted?'retired':s.won?'goal_clear':platform?'health_depleted':'base_destroyed'});};
 const pause=()=>{if(run.finished||!run.started||run.paused)return;run.paused=true;clearKeys();overlay.hidden=false;q('#adv-overlay-title').textContent='喘口气，再继续';q('#adv-overlay-copy').textContent='本局已暂停，切回页面后点击继续。';q('[data-adv-resume]').textContent='继续游戏 →';if(!q('[data-adv-settle]')){const b=document.createElement('button');b.dataset.advSettle='';b.className='adventure-settle';b.textContent='结束并保存成绩';q('[data-adv-resume]').after(b);on(b,'click',()=>finish(true));}q('[data-adv-pause]').textContent='继续';q('[data-adv-pause]').setAttribute('aria-label','继续游戏');q('[data-adv-resume]').focus();updateHud()};
 const resume=()=>{run.started=true;run.paused=false;clearKeys();overlay.hidden=true;last=performance.now();carry=0;q('[data-adv-pause]').textContent='暂停';q('[data-adv-pause]').setAttribute('aria-label','暂停游戏');canvas.focus({preventScroll:true});updateHud()};
 on(q('[data-adv-resume]'),'click',resume);on(q('[data-adv-pause]'),'click',()=>run.paused?resume():pause());
 on(q('[data-adv-sound]'),'click',async()=>{run.sound=!run.sound;if(run.sound){const AC=window.AudioContext||window.webkitAudioContext;if(AC){run.audio||=new AC();await run.audio.resume().catch(()=>{});}else run.sound=false;}q('[data-adv-sound]').textContent=`音效：${run.sound?'开':'关'}`;q('[data-adv-sound]').setAttribute('aria-pressed',String(run.sound));q('[data-adv-sound]').setAttribute('aria-label',run.sound?'关闭游戏音效':'开启游戏音效')});
 const choose=type=>{tool=type;document.querySelectorAll('[data-tower]').forEach(b=>{b.classList.toggle('selected',b.dataset.tower===type);b.setAttribute('aria-pressed',String(b.dataset.tower===type))});updateHud()};
 const action=a=>{if(run.paused||run.finished)return;const result=nightwatchAction(s,a);if(result?.message){feedback=result.message;feedbackUntil=performance.now()+2200;}updateHud()};
 const selectCell=c=>{cell=c;s.selectedCell=c;const occupied=s.towers.some(t=>t.row===c.row&&t.col===c.col);if(!occupied)action({type:'build',...c,tower:tool});updateHud()};
 if(!platform){on(canvas,'pointerdown',e=>{if(run.paused)return;const r=canvas.getBoundingClientRect(),c=nightwatchCellAt((e.clientX-r.left)*960/r.width,(e.clientY-r.top)*540/r.height);if(c){e.preventDefault();selectCell(c);canvas.focus({preventScroll:true})}});document.querySelectorAll('[data-tower]').forEach(b=>on(b,'click',()=>choose(b.dataset.tower)));document.querySelectorAll('[data-tower-action]').forEach(b=>on(b,'click',()=>action({type:b.dataset.towerAction,...cell})));on(q('[data-tower-wave]'),'click',()=>action({type:'wave'}));}
 const keyMap={ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Space:'jump',ArrowUp:'jump',KeyW:'jump',KeyX:'dash',ShiftLeft:'dash',ShiftRight:'dash'};
 on(window,'keydown',e=>{if(run.finished)return;if(['KeyP','Escape'].includes(e.code)){e.preventDefault();if(!e.repeat)run.paused?resume():pause();return;}if(run.paused)return;if(platform){const k=keyMap[e.code];if(k){e.preventDefault();held.add(k);updateKeys()}}else{const n=Number(e.key);if(n>=1&&n<=4){choose(TOWER_TYPES[n-1].id);e.preventDefault()}const d={ArrowLeft:[0,-1],ArrowRight:[0,1],ArrowUp:[-1,0],ArrowDown:[1,0]}[e.code];if(d){e.preventDefault();cell={row:Math.max(0,Math.min(4,cell.row+d[0])),col:Math.max(0,Math.min(6,cell.col+d[1]))};s.selectedCell=cell;updateHud()}if(e.code==='Space'){e.preventDefault();if(!e.repeat)selectCell(cell)}if(e.code==='KeyU'&&!e.repeat)action({type:'upgrade',...cell});if(e.code==='KeyN'&&!e.repeat)action({type:'wave'});}});
 on(window,'keyup',e=>{if(keyMap[e.code]){held.delete(keyMap[e.code]);updateKeys()}});on(window,'blur',pause);on(document,'visibilitychange',()=>{if(document.hidden)pause()});
 document.querySelectorAll('[data-adv-key]').forEach(b=>{on(b,'pointerdown',e=>{if(run.paused)return;e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,b.dataset.advKey);b.classList.add('held');updateKeys()});const release=e=>{pointers.delete(e.pointerId);b.classList.remove('held');updateKeys()};on(b,'pointerup',release);on(b,'pointercancel',release);on(b,'lostpointercapture',release)});
 const frame=now=>{if(active!==run||run.finished)return;const dt=Math.min(.1,(now-last)/1000);last=now;if(!run.paused){carry+=dt;while(carry>=1/120&&!s.over){if(platform)stepPlatformer(s,1/120,keys);else stepNightwatch(s,1/120);carry-=1/120;}hudCarry+=dt;if(hudCarry>.08){updateHud();hudCarry=0}}draw(ctx,s,960,540);if(s.over){updateHud();finish();return}run.raf=requestAnimationFrame(frame)};
 updateHud();draw(ctx,s,960,540);run.raf=requestAnimationFrame(frame);
}
